### PR TITLE
Update to the latest version of PS2SDK.

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by F0bes** [comment]
Thanks, works good!

**Comment by Wolf3s** [comment]
> Thanks, works good!

Did you tested with a real ps2 mouse?

**Comment by F0bes** [comment]
I tested with my generic mouse with my PS2.

**Comment by Wolf3s** [comment]
> I tested with my generic mouse with my PS2.

Nice, i'm planning to update some repositories to the latest sdk.

**Pull request merged**
